type: pipeline
description: "Train using TF component"

jobs:
  tf_job:
    type: component
    component: file:./component.yml
    compute: azureml:gpu-cluster
    inputs:
      epochs: 1
    outputs:
      trained-model-output:
        mode: upload
    overrides:
      resources:
        instance_count: 3
      distribution:
        type: tensorflow
        worker_count: 3

        
