# yaml-language-server: $schema=https://azuremlsdk2.blob.core.windows.net/latest/environment.schema.json
name: TestEnv
version: 1
path: environment_files
docker:
   image: mcr.microsoft.com/azureml/base:0.2.2
