# common variables
variables:
  currentDir: $(System.DefaultWorkingDirectory)
  scriptPath: $(System.DefaultWorkingDirectory)/scripts
  packageName: azure.ml
  testPath: $(System.DefaultWorkingDirectory)/tests
  unittestTestPath: $(System.DefaultWorkingDirectory)/tests/azure-ml/unittests
  e2ETestPath: $(System.DefaultWorkingDirectory)/tests/azure-ml/e2etests
  pythonVersion: 3.6
  coverageThreshold: '70'
  poolName: Vienna SDK Windows
  srcPath: $(System.DefaultWorkingDirectory)/src
  email: amlrelsa@microsoft.com
  user: amlrelsa-ms
