# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  - template: config/vars.yml
pool:
  name: $(poolName)
steps:
- template: ./templates/sdk_setup/template-sdk-setup.yml
- task: AzureCLI@2
  displayName: 'Copy yaml schema to blob'
  inputs:
    azureSubscription: 'INFRA Project Vienna INT (589c7ae9-223e-45e3-a191-98433e0821a9)'
    scriptType: batch
    scriptLocation: inlineScript
    inlineScript: |
     python extension/generator.py
     az storage blob upload-batch -d latest -s extension/schema --account-name azuremlsdk2
