<<<<<<< HEAD
$schema: https://azuremlsdk2.blob.core.windows.net/latest/environment.schema.json
=======
$schema=https://azuremlsdk2.blob.core.windows.net/latest/environment.schema.json
>>>>>>> main
name: TestEnv
version: 1
path: environment_files
conda_file: file:environment.yml
