# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: (^autorest/)|(^src/cli/src/machinelearningservices/(README.md|setup.py|azext_ml/manual/__init__.py))|(^src/azure-ml/azure/ml/_restclient/)|(^src/azure-ml/azure/ml/_vendor/)

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-merge-conflict
-   repo: https://github.com/psf/black
    rev: 20.8b1 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
    -   id: black
        language_version: python3 # Should be a command that runs python3.6+
        args:
        -   "--line-length=120"
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: flake8
