# https://aka.ms/yaml
trigger:
- master

variables:
  - template: config/vars.yml

pool:
  name: $(poolName)

steps:
- checkout: self
- template: ./templates/sdk_setup/template-sdk-setup.yml
- template: ./templates/coveragetests/template-coverage-tests.yml
  parameters:
    packageName: $(packageName)
    testPath: $(e2ETestPath)
    coverage: true
