# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  - template: config/vars.yml
pool:
  name: $(poolName)
steps:
- template: templates/sdk_setup/template-python.yml
- bash: |
   python -m pip install pip==20.1.1 --disable-pip-version-check
   pip install flake8==3.4.1 --disable-pip-version-check 
   python ./scripts/code_health.py --testpath "${{variables.srcPath}}"
  displayName: 'Run flake8'