# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- releases/*

variables:
  - template: config/vars.yml

pool:
  name: $(poolName)

steps:
- checkout: self
  persistCredentials: true
- template: templates/sdk_setup/template-python.yml
- template: templates/sdk_setup/template-sdk-setup.yml
- script: python $(scriptPath)\dev_setup.py -cv
  displayName: "Setup CLI"
- script: python $(scriptPath)\dev_setup.py -wv
  displayName: "Build Wheels"
- script: |
   git config user.email $(email)
   git config user.name $(user)

   git checkout -b release_update/sdk_cli_v2 --force
   
   git add .
   git commit -m "update samples from sdk_cli_v2 as a part of SDK release"
   git push origin release_update/sdk_cli_v2 --force
   
  displayName: CreateBranch
- task: AzurePowerShell@2
  displayName: '[PipelineSetup]:Build-Publish-IndexUpdate'
  inputs:
    azureSubscription: 'INFRA Project Vienna INT (589c7ae9-223e-45e3-a191-98433e0821a9)'
    ScriptType: InlineScript
    Inline: |
      Set-Location -Path  $(System.DefaultWorkingDirectory)
      $(scriptPath)\publish_packages.ps1 -config .\scripts\configs\sdk-test.template -source .\src -prefix sdk-cli-v2/$(Build.BuildId)/
      echo "Update to Pypi"
      $(scriptPath)\update_pypi_index.ps1 -config .\scripts\configs\sdk-test.template -prefix sdk-cli-v2/$(Build.BuildId)/
     
    azurePowerShellVersion: LatestVersion
