# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  - template: config/vars.yml
pool:
  name: $(poolName)
steps:
- checkout: self
- template: templates/sdk_setup/template-python.yml
- template: templates/sdk_setup/template-sdk-setup.yml
- script: |
   python ./scripts/run_mypy.py -s ./src/azure-ml >> ../type_checking.txt

   
   echo "========MYPY OUTPUT========"
   cat ../type_checking.txt
   
   echo
   echo "========MYPY ERRORS========"
   grep -E "^.*?[0-9]+: error:" ../type_checking.txt >&2 || true
  failOnStderr: true
  displayName: 'Run Mypy'
  
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/cobertura.xml'
    failIfCoverageEmpty: false
