# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Vienna SDK Windows

variables:
  ScriptPath: $(System.DefaultWorkingDirectory)\pipelines\scripts
  PackageName: azure.ml
  TestPath: $(System.DefaultWorkingDirectory)\tests
  PackageTestPath: $(System.DefaultWorkingDirectory)\tests\azure-ml\unittests
  CurrentDir: $(System.DefaultWorkingDirectory)

steps:
- checkout: self

- task: UsePythonVersion@0
  displayName: 'Use Python 3.6.x'
  inputs:
    versionSpec: 3.6.x
- task: Npm@1
  displayName: 'Install autorest'
  inputs:
    command: 'custom'
    customCommand: 'install -g autorest'
- template: ./templates/sdk_setup/template-sdk-setup.yml

- script: |
   python ./scripts/run_mypy.py -s .\src\azure-ml >> ../type_checking.txt

   
   echo "========MYPY OUTPUT========"
   cat ..\type_checking.txt
   
   echo
   echo "========MYPY ERRORS========"
   grep -E "^.*?[0-9]+: error:" ../type_checking.txt >&2 || true
  failOnStderr: true
  displayName: 'Run Mypy'
  
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/cobertura.xml'
    failIfCoverageEmpty: false
