name: akstest
type: online
infrastructure: azureml:devplatv2aks
auth_mode: Key
traffic:
    etblue: 50
    etgreen: 50
deployments:
    etblue:   
        model:
            name: my-model-1
            version: 1
            asset_path: model/model.pkl
        code_configuration:
            code:
                directory: code
            scoring_script: main.py
        environment:
            name: sklearn-aks-env
            version: 1
            path: .
            conda_file: environment/conda.yml
        scale_settings:
            scale_type: manual
            instance_count: 1
        request_settings:
            request_timeout_ms: 3000
            max_concurrent_requests_per_instance: 1
            max_queue_wait_ms: 3000
        resource_requirements:
            cpu: 1.5
            # memory_in_gb: 1.0
    etgreen:   
        model:
            name: my-model-2
            version: 1
            asset_path: model/model.pkl
        code_configuration:
            code:
                directory: code
            scoring_script: main.py
        environment:
            name: sklearn-aks-env
            version: 1
            path: .
            conda_file: environment/conda.yml
        scale_settings:
            scale_type: manual
            instance_count: 1
        request_settings:
            request_timeout_ms: 3000
            max_concurrent_requests_per_instance: 1
            max_queue_wait_ms: 3000
        resource_requirements:
            cpu: 1.5
            # memory_in_gb: 1.0
