name: Greetings

on: [push]

jobs:
  pull-src:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
    - run: git clone https://user:${{ secrets.AZDEVOPS_PAT }}@msdata.visualstudio.com/DefaultCollection/Vienna/_git/sdk-cli-v2  sdk-src
    - run: ls
      working-directory: sdk-src
    - run: git add .
      working-directory: sdk-src
    - run: git config --global user.email "azureml@microsoft.com"
    - run: git config --global user.name "Azure ML"
    - run: git commit -m "pulling v2 src in"
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: \{{ secrets.GITHUB_TOKEN }}
        branch: main
