name: Greetings

on: [push]

jobs:
  dev-setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sdk2-src
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
    - name: Setup Python
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.7
    - run: sudo npm install -g autorest
    - run: python scripts/dev_setup.py -sdk
    - run: python scripts/dev_setup.py -cli
    - run: pip install -e ./src/cli/src/machinelearningservices
    - run: az extension list
    - run: az ml -h
