name: Build and run CLI

on: 
  push:
    branches:
      - main
    paths-ignore:
    - 'website/**'
jobs:
  dev-setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sdk2-src
    env:
      AZURE_EXTENSION_DIR: ${{ github.workspace }}/sdk2-src/src/cli/src 
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
    - name: Setup Python
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.7
    - name: Cache CLI
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ${{ github.workspace }}/sdk2-src/src/cli/src 
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('sdk2-src/**') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-   
    - run: sudo npm install -g autorest
    - run: python scripts/dev_setup.py -s
    - run: python scripts/dev_setup.py -c
    - run: echo $GITHUB_WORKSPACE
 #   - run: pip install -e ./src/cli/src/machinelearningservices
 #   - run: echo $AZURE_EXTENSION _DIR
    - run: az extension list
    - run: az ml -h
    - run: az ml job -h
    - name: Upload a Bu   ild Artifact
      uses: actions/upr: true
