name: Greetings

on: [push]

jobs:
  dev-setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
    - name: Setup Python
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.7
    - run: npm install -autorest
    - run: python sdk2-src/scripts/dev_setup.py -sdk
    - run: python sdk2-src/scripts/dev_setup.py -cli
