name: Run CLI from whl

on: 
  push:
    branches:
      - main
    paths-ignore:
    - 'website/**'
jobs:
  dev-setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
    - name: Setup Python
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.7
    - run: az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/26401099/ml-0.0.2-py3-none-any.whl --pip-extra-index-urls https://azuremlsdktestpypi.azureedge.net/sdk-cli-v2/26401099 -y
    - run: az ml -h
    - run: az ml job -h
    - run: az ml data -h
    - run: az ml datastore -h
    - run: az ml model -h
    - run: az ml environment -h
    - run: az ml endpoint -h
    - run: az ml compute -h
    - run: az ml workspace -h
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_TOKEN}}
    - run: az config set defaults.workspace=devplatv2
    - run: az config set defaults.group=demorg
    - run: az account set -s 92c76a2f-0e1c-4216-b65e-abf7a3f34c1e
    - run: az ml data create --file examples/blob_dataset.yml
      continue-on-error: true
    - run: az ml environment create --file examples/fastai-vision-env.yml
      continue-on-error: true
    - run: az ml job create --file examples/commandjob.yml  --name helloworld_$GITHUB_RUN_ID --query metadata.interaction_endpoints.studio
      continue-on-error: true
    - run: az ml job create --file examples/fastai_mnist_job.yml --name fastai_mnist_$GITHUB_RUN_ID --query metadata.interaction_endpoints.studio
      continue-on-error: true
    - run: az ml job create --file examples/fastai_pets_job.yml --name fastai_pets_$GITHUB_RUN_ID --query metadata.interaction_endpoints.studio
      continue-on-error: true
