name: sphinx-docs
on:
  push:
    branches:
      - main
    paths: 
      - docs/**
      - .github/workflows/sphinx-docs.yml
  pull_request:
    branches: 
      - main
    paths:
      - docs/**
      - .github/workflows/sphinx-docs.yml
jobs:
  build:
    name: Push Sphinx Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git checkout -b sphinx-docs
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: docs
      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationHTML
          path: docs/_build/html/
      - run: git config --global user.email "azureml@microsoft.com"
      - run: git config --global user.name "Azure ML"
      - run: git add -f docs
      - run: git commit -m "adding built sphinx docs"
      - run: git push
