# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hi'
      - run: echo 'prepped'
  train:
    needs: prep
    runs-on: ubuntu-latest
    steps:
      - run: echo 'model'
      - run: echo 'created'
  test:
    needs: train
    runs-on: ubuntu-latest
    steps:
      - run: echo 'tested!' 
